language: php
services: mongodb

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: TARGET=phpcs
    - php: '7.1'
      env: TARGET=phpmd
    - php: '7.1'
      env: TARGET=phpunit

before_script:
    - pecl -q install mongodb && echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer self-update
    - composer install
    - mongo mydb_test --eval 'db.addUser("travis", "test");'
    - mongo mydb_test --eval "db.people.insertMany([{name: 'Olexandr', age: 20, status: 'coding'}, {name: 'Anastasia', age: 27, status: 'waiting'}, {name: 'Fred', age:34, status: 'chilling'}]);"
#    - if [ "$TARGET" = "phpunit" ]; then ./install.sh; fi

script:
  - if [ "$TARGET" = "phpmd" ];   then bin/phpmd ./src text ./.phpmd-ruleset.xml; fi
  - if [ "$TARGET" = "phpcs" ];   then bin/phpcs ./src/controllers.php --standard=PSR2 --extensions=php -p; fi
  - if [ "$TARGET" = "phpcs" ];   then bin/phpcs ./src/Entity --standard=PSR2 --extensions=php -p; fi
  - if [ "$TARGET" = "phpunit" ];   then bin/phpunit ./tests ; fi
